version: '3'
services:
  zcs:
    image: anhit:zcsub2004
    container_name: zcs
    hostname: mail.domain.local
    ports:
      - '25:25'
      - '80:80'
      - '443:443'
      - '465:465'
      - '587:587'
      - '993:993'
      - '995:995'
      - '7071:7071'
    volumes:
      - ./zimbra:/opt/zimbra
    restart: always